language: node_js
sudo: false
node_js:
- stable
- 7
- 6
cache:
  directories:
  - node_modules
env:
  matrix:
  - CMD=lint
  - CMD=test
  - CMD=flow
matrix:
  fast_finish: true
  allow_failures:
  - env: CMD=flow
script:
- yarn $CMD
after_success:
- '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && npm run coverage'
notifications:
  email: false
  slack:
    secure: qDisnttj7h7QGW85NRYOOX+Mj+y5QSd4k6JtmdqPNkneE7CNH4phJLyOaOwjvMMknEwvBdhSww6e1Z/tnUDA69J1wxzMmO7U1mHpUq6jj38dVb3C4rPh3toyGD2hjtJl/F069R1e3jeqESzz/dBTh+oWq/ZTgS758qfP3YdkF11CG/5N6ERoWSv+Dk5MY6EU3HglklqApUTKLDEz6cqae7nfcngR610JkykjIr6neDgmFnGKvtX0BaWmjl69DmB0/98yzNWWgdSrjTQKp/auiNOy8BVdVe6HlPIoJaJxKzUTi7WYTTIBiRfpMOOR5ZCs6Ek4p4BnR7Rs/er/sVrhrfWjMvRl0LY3LOTnEhtocBWWNZ+5J6blNbqEViokyoFLGAFR4B5y+PZUMC4NqayRy4BwmAp3P1kgVl/gWoRz5mQ84xZCS9779SvCK4xf0ZbKau6yUcVBJNvyV7IW0403A/DR8i4Le44e+YAV25W5/w+HrJ5jGhCruV10/kNtjbVq2mcn6BTIGyayLSTnAG51NkNmioCuAUiLHzCd2rbmOHoamEPiZX/dMWmnuj2qQno2HyOPAIKnJOttm21tEpXzS+IHwvbo2TMrQnNIvZAm9aSpv+Ku08AWGxVY6ZdYlGyuKwmUIo7jWAoGMIyCRaYeEJSDsGUsPX9Ghorb13dUIfs=
